// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyber/proto/dag_conf.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cyber/proto/dag_conf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace cyber {
namespace proto {
class ComponentInfoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ComponentInfo> {
} _ComponentInfo_default_instance_;
class TimerComponentInfoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<TimerComponentInfo> {
} _TimerComponentInfo_default_instance_;
class ModuleConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ModuleConfig> {
} _ModuleConfig_default_instance_;
class DagConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<DagConfig> {
} _DagConfig_default_instance_;

namespace protobuf_cyber_2fproto_2fdag_5fconf_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[4];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComponentInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComponentInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComponentInfo, class_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ComponentInfo, config_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TimerComponentInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TimerComponentInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TimerComponentInfo, class_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TimerComponentInfo, config_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModuleConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModuleConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModuleConfig, module_library_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModuleConfig, components_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModuleConfig, timer_components_),
  0,
  ~0u,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DagConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DagConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DagConfig, module_config_),
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(ComponentInfo)},
  { 9, 16, sizeof(TimerComponentInfo)},
  { 18, 26, sizeof(ModuleConfig)},
  { 29, 35, sizeof(DagConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ComponentInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_TimerComponentInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ModuleConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_DagConfig_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cyber/proto/dag_conf.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

}  // namespace

void TableStruct::Shutdown() {
  _ComponentInfo_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _TimerComponentInfo_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _ModuleConfig_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _DagConfig_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::apollo::cyber::proto::protobuf_cyber_2fproto_2fcomponent_5fconf_2eproto::InitDefaults();
  _ComponentInfo_default_instance_.DefaultConstruct();
  _TimerComponentInfo_default_instance_.DefaultConstruct();
  _ModuleConfig_default_instance_.DefaultConstruct();
  _DagConfig_default_instance_.DefaultConstruct();
  _ComponentInfo_default_instance_.get_mutable()->config_ = const_cast< ::apollo::cyber::proto::ComponentConfig*>(
      ::apollo::cyber::proto::ComponentConfig::internal_default_instance());
  _TimerComponentInfo_default_instance_.get_mutable()->config_ = const_cast< ::apollo::cyber::proto::TimerComponentConfig*>(
      ::apollo::cyber::proto::TimerComponentConfig::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\032cyber/proto/dag_conf.proto\022\022apollo.cyb"
      "er.proto\032 cyber/proto/component_conf.pro"
      "to\"X\n\rComponentInfo\022\022\n\nclass_name\030\001 \001(\t\022"
      "3\n\006config\030\002 \001(\0132#.apollo.cyber.proto.Com"
      "ponentConfig\"b\n\022TimerComponentInfo\022\022\n\ncl"
      "ass_name\030\001 \001(\t\0228\n\006config\030\002 \001(\0132(.apollo."
      "cyber.proto.TimerComponentConfig\"\237\001\n\014Mod"
      "uleConfig\022\026\n\016module_library\030\001 \001(\t\0225\n\ncom"
      "ponents\030\002 \003(\0132!.apollo.cyber.proto.Compo"
      "nentInfo\022@\n\020timer_components\030\003 \003(\0132&.apo"
      "llo.cyber.proto.TimerComponentInfo\"D\n\tDa"
      "gConfig\0227\n\rmodule_config\030\001 \003(\0132 .apollo."
      "cyber.proto.ModuleConfig"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 504);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cyber/proto/dag_conf.proto", &protobuf_RegisterTypes);
  ::apollo::cyber::proto::protobuf_cyber_2fproto_2fcomponent_5fconf_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cyber_2fproto_2fdag_5fconf_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ComponentInfo::kClassNameFieldNumber;
const int ComponentInfo::kConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ComponentInfo::ComponentInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.ComponentInfo)
}
ComponentInfo::ComponentInfo(const ComponentInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  class_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_class_name()) {
    class_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.class_name_);
  }
  if (from.has_config()) {
    config_ = new ::apollo::cyber::proto::ComponentConfig(*from.config_);
  } else {
    config_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.ComponentInfo)
}

void ComponentInfo::SharedCtor() {
  _cached_size_ = 0;
  class_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  config_ = NULL;
}

ComponentInfo::~ComponentInfo() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.ComponentInfo)
  SharedDtor();
}

void ComponentInfo::SharedDtor() {
  class_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete config_;
  }
}

void ComponentInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ComponentInfo::descriptor() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ComponentInfo& ComponentInfo::default_instance() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  return *internal_default_instance();
}

ComponentInfo* ComponentInfo::New(::google::protobuf::Arena* arena) const {
  ComponentInfo* n = new ComponentInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ComponentInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.ComponentInfo)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_class_name()) {
      GOOGLE_DCHECK(!class_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*class_name_.UnsafeRawStringPointer())->clear();
    }
    if (has_config()) {
      GOOGLE_DCHECK(config_ != NULL);
      config_->::apollo::cyber::proto::ComponentConfig::Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ComponentInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.ComponentInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string class_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_class_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->class_name().data(), this->class_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.ComponentInfo.class_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.cyber.proto.ComponentConfig config = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.ComponentInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.ComponentInfo)
  return false;
#undef DO_
}

void ComponentInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.ComponentInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string class_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->class_name().data(), this->class_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.ComponentInfo.class_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->class_name(), output);
  }

  // optional .apollo.cyber.proto.ComponentConfig config = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->config_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.ComponentInfo)
}

::google::protobuf::uint8* ComponentInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.ComponentInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string class_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->class_name().data(), this->class_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.ComponentInfo.class_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->class_name(), target);
  }

  // optional .apollo.cyber.proto.ComponentConfig config = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->config_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.ComponentInfo)
  return target;
}

size_t ComponentInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.ComponentInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string class_name = 1;
    if (has_class_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->class_name());
    }

    // optional .apollo.cyber.proto.ComponentConfig config = 2;
    if (has_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->config_);
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ComponentInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.ComponentInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ComponentInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ComponentInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.ComponentInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.ComponentInfo)
    MergeFrom(*source);
  }
}

void ComponentInfo::MergeFrom(const ComponentInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.ComponentInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_class_name();
      class_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.class_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_config()->::apollo::cyber::proto::ComponentConfig::MergeFrom(from.config());
    }
  }
}

void ComponentInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.ComponentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ComponentInfo::CopyFrom(const ComponentInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.ComponentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ComponentInfo::IsInitialized() const {
  return true;
}

void ComponentInfo::Swap(ComponentInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ComponentInfo::InternalSwap(ComponentInfo* other) {
  class_name_.Swap(&other->class_name_);
  std::swap(config_, other->config_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ComponentInfo::GetMetadata() const {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ComponentInfo

// optional string class_name = 1;
bool ComponentInfo::has_class_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ComponentInfo::set_has_class_name() {
  _has_bits_[0] |= 0x00000001u;
}
void ComponentInfo::clear_has_class_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void ComponentInfo::clear_class_name() {
  class_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_class_name();
}
const ::std::string& ComponentInfo::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ComponentInfo.class_name)
  return class_name_.GetNoArena();
}
void ComponentInfo::set_class_name(const ::std::string& value) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ComponentInfo.class_name)
}
#if LANG_CXX11
void ComponentInfo::set_class_name(::std::string&& value) {
  set_has_class_name();
  class_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ComponentInfo.class_name)
}
#endif
void ComponentInfo::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ComponentInfo.class_name)
}
void ComponentInfo::set_class_name(const char* value, size_t size) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ComponentInfo.class_name)
}
::std::string* ComponentInfo::mutable_class_name() {
  set_has_class_name();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ComponentInfo.class_name)
  return class_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ComponentInfo::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ComponentInfo.class_name)
  clear_has_class_name();
  return class_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ComponentInfo::set_allocated_class_name(::std::string* class_name) {
  if (class_name != NULL) {
    set_has_class_name();
  } else {
    clear_has_class_name();
  }
  class_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), class_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ComponentInfo.class_name)
}

// optional .apollo.cyber.proto.ComponentConfig config = 2;
bool ComponentInfo::has_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ComponentInfo::set_has_config() {
  _has_bits_[0] |= 0x00000002u;
}
void ComponentInfo::clear_has_config() {
  _has_bits_[0] &= ~0x00000002u;
}
void ComponentInfo::clear_config() {
  if (config_ != NULL) config_->::apollo::cyber::proto::ComponentConfig::Clear();
  clear_has_config();
}
const ::apollo::cyber::proto::ComponentConfig& ComponentInfo::config() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ComponentInfo.config)
  return config_ != NULL ? *config_
                         : *::apollo::cyber::proto::ComponentConfig::internal_default_instance();
}
::apollo::cyber::proto::ComponentConfig* ComponentInfo::mutable_config() {
  set_has_config();
  if (config_ == NULL) {
    config_ = new ::apollo::cyber::proto::ComponentConfig;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ComponentInfo.config)
  return config_;
}
::apollo::cyber::proto::ComponentConfig* ComponentInfo::release_config() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ComponentInfo.config)
  clear_has_config();
  ::apollo::cyber::proto::ComponentConfig* temp = config_;
  config_ = NULL;
  return temp;
}
void ComponentInfo::set_allocated_config(::apollo::cyber::proto::ComponentConfig* config) {
  delete config_;
  config_ = config;
  if (config) {
    set_has_config();
  } else {
    clear_has_config();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ComponentInfo.config)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TimerComponentInfo::kClassNameFieldNumber;
const int TimerComponentInfo::kConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TimerComponentInfo::TimerComponentInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.TimerComponentInfo)
}
TimerComponentInfo::TimerComponentInfo(const TimerComponentInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  class_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_class_name()) {
    class_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.class_name_);
  }
  if (from.has_config()) {
    config_ = new ::apollo::cyber::proto::TimerComponentConfig(*from.config_);
  } else {
    config_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.TimerComponentInfo)
}

void TimerComponentInfo::SharedCtor() {
  _cached_size_ = 0;
  class_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  config_ = NULL;
}

TimerComponentInfo::~TimerComponentInfo() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.TimerComponentInfo)
  SharedDtor();
}

void TimerComponentInfo::SharedDtor() {
  class_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete config_;
  }
}

void TimerComponentInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TimerComponentInfo::descriptor() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TimerComponentInfo& TimerComponentInfo::default_instance() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  return *internal_default_instance();
}

TimerComponentInfo* TimerComponentInfo::New(::google::protobuf::Arena* arena) const {
  TimerComponentInfo* n = new TimerComponentInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TimerComponentInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.TimerComponentInfo)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_class_name()) {
      GOOGLE_DCHECK(!class_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*class_name_.UnsafeRawStringPointer())->clear();
    }
    if (has_config()) {
      GOOGLE_DCHECK(config_ != NULL);
      config_->::apollo::cyber::proto::TimerComponentConfig::Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TimerComponentInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.TimerComponentInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string class_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_class_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->class_name().data(), this->class_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.TimerComponentInfo.class_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.cyber.proto.TimerComponentConfig config = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.TimerComponentInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.TimerComponentInfo)
  return false;
#undef DO_
}

void TimerComponentInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.TimerComponentInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string class_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->class_name().data(), this->class_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.TimerComponentInfo.class_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->class_name(), output);
  }

  // optional .apollo.cyber.proto.TimerComponentConfig config = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->config_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.TimerComponentInfo)
}

::google::protobuf::uint8* TimerComponentInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.TimerComponentInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string class_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->class_name().data(), this->class_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.TimerComponentInfo.class_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->class_name(), target);
  }

  // optional .apollo.cyber.proto.TimerComponentConfig config = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->config_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.TimerComponentInfo)
  return target;
}

size_t TimerComponentInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.TimerComponentInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string class_name = 1;
    if (has_class_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->class_name());
    }

    // optional .apollo.cyber.proto.TimerComponentConfig config = 2;
    if (has_config()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->config_);
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TimerComponentInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.TimerComponentInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const TimerComponentInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TimerComponentInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.TimerComponentInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.TimerComponentInfo)
    MergeFrom(*source);
  }
}

void TimerComponentInfo::MergeFrom(const TimerComponentInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.TimerComponentInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_class_name();
      class_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.class_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_config()->::apollo::cyber::proto::TimerComponentConfig::MergeFrom(from.config());
    }
  }
}

void TimerComponentInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.TimerComponentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TimerComponentInfo::CopyFrom(const TimerComponentInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.TimerComponentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TimerComponentInfo::IsInitialized() const {
  return true;
}

void TimerComponentInfo::Swap(TimerComponentInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TimerComponentInfo::InternalSwap(TimerComponentInfo* other) {
  class_name_.Swap(&other->class_name_);
  std::swap(config_, other->config_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TimerComponentInfo::GetMetadata() const {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TimerComponentInfo

// optional string class_name = 1;
bool TimerComponentInfo::has_class_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void TimerComponentInfo::set_has_class_name() {
  _has_bits_[0] |= 0x00000001u;
}
void TimerComponentInfo::clear_has_class_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void TimerComponentInfo::clear_class_name() {
  class_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_class_name();
}
const ::std::string& TimerComponentInfo::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TimerComponentInfo.class_name)
  return class_name_.GetNoArena();
}
void TimerComponentInfo::set_class_name(const ::std::string& value) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.TimerComponentInfo.class_name)
}
#if LANG_CXX11
void TimerComponentInfo::set_class_name(::std::string&& value) {
  set_has_class_name();
  class_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.TimerComponentInfo.class_name)
}
#endif
void TimerComponentInfo::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.TimerComponentInfo.class_name)
}
void TimerComponentInfo::set_class_name(const char* value, size_t size) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.TimerComponentInfo.class_name)
}
::std::string* TimerComponentInfo::mutable_class_name() {
  set_has_class_name();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TimerComponentInfo.class_name)
  return class_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* TimerComponentInfo::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TimerComponentInfo.class_name)
  clear_has_class_name();
  return class_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void TimerComponentInfo::set_allocated_class_name(::std::string* class_name) {
  if (class_name != NULL) {
    set_has_class_name();
  } else {
    clear_has_class_name();
  }
  class_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), class_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TimerComponentInfo.class_name)
}

// optional .apollo.cyber.proto.TimerComponentConfig config = 2;
bool TimerComponentInfo::has_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void TimerComponentInfo::set_has_config() {
  _has_bits_[0] |= 0x00000002u;
}
void TimerComponentInfo::clear_has_config() {
  _has_bits_[0] &= ~0x00000002u;
}
void TimerComponentInfo::clear_config() {
  if (config_ != NULL) config_->::apollo::cyber::proto::TimerComponentConfig::Clear();
  clear_has_config();
}
const ::apollo::cyber::proto::TimerComponentConfig& TimerComponentInfo::config() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TimerComponentInfo.config)
  return config_ != NULL ? *config_
                         : *::apollo::cyber::proto::TimerComponentConfig::internal_default_instance();
}
::apollo::cyber::proto::TimerComponentConfig* TimerComponentInfo::mutable_config() {
  set_has_config();
  if (config_ == NULL) {
    config_ = new ::apollo::cyber::proto::TimerComponentConfig;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TimerComponentInfo.config)
  return config_;
}
::apollo::cyber::proto::TimerComponentConfig* TimerComponentInfo::release_config() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TimerComponentInfo.config)
  clear_has_config();
  ::apollo::cyber::proto::TimerComponentConfig* temp = config_;
  config_ = NULL;
  return temp;
}
void TimerComponentInfo::set_allocated_config(::apollo::cyber::proto::TimerComponentConfig* config) {
  delete config_;
  config_ = config;
  if (config) {
    set_has_config();
  } else {
    clear_has_config();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TimerComponentInfo.config)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ModuleConfig::kModuleLibraryFieldNumber;
const int ModuleConfig::kComponentsFieldNumber;
const int ModuleConfig::kTimerComponentsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ModuleConfig::ModuleConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.ModuleConfig)
}
ModuleConfig::ModuleConfig(const ModuleConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      components_(from.components_),
      timer_components_(from.timer_components_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  module_library_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_module_library()) {
    module_library_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.module_library_);
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.ModuleConfig)
}

void ModuleConfig::SharedCtor() {
  _cached_size_ = 0;
  module_library_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ModuleConfig::~ModuleConfig() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.ModuleConfig)
  SharedDtor();
}

void ModuleConfig::SharedDtor() {
  module_library_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ModuleConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ModuleConfig::descriptor() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ModuleConfig& ModuleConfig::default_instance() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  return *internal_default_instance();
}

ModuleConfig* ModuleConfig::New(::google::protobuf::Arena* arena) const {
  ModuleConfig* n = new ModuleConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ModuleConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.ModuleConfig)
  components_.Clear();
  timer_components_.Clear();
  if (has_module_library()) {
    GOOGLE_DCHECK(!module_library_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*module_library_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ModuleConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.ModuleConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string module_library = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_module_library()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->module_library().data(), this->module_library().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.ModuleConfig.module_library");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .apollo.cyber.proto.ComponentInfo components = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_components()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_timer_components()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.ModuleConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.ModuleConfig)
  return false;
#undef DO_
}

void ModuleConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.ModuleConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string module_library = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->module_library().data(), this->module_library().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.ModuleConfig.module_library");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->module_library(), output);
  }

  // repeated .apollo.cyber.proto.ComponentInfo components = 2;
  for (unsigned int i = 0, n = this->components_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->components(i), output);
  }

  // repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
  for (unsigned int i = 0, n = this->timer_components_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->timer_components(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.ModuleConfig)
}

::google::protobuf::uint8* ModuleConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.ModuleConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string module_library = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->module_library().data(), this->module_library().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.ModuleConfig.module_library");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->module_library(), target);
  }

  // repeated .apollo.cyber.proto.ComponentInfo components = 2;
  for (unsigned int i = 0, n = this->components_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->components(i), deterministic, target);
  }

  // repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
  for (unsigned int i = 0, n = this->timer_components_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->timer_components(i), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.ModuleConfig)
  return target;
}

size_t ModuleConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.ModuleConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .apollo.cyber.proto.ComponentInfo components = 2;
  {
    unsigned int count = this->components_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->components(i));
    }
  }

  // repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
  {
    unsigned int count = this->timer_components_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->timer_components(i));
    }
  }

  // optional string module_library = 1;
  if (has_module_library()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->module_library());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ModuleConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.ModuleConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const ModuleConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ModuleConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.ModuleConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.ModuleConfig)
    MergeFrom(*source);
  }
}

void ModuleConfig::MergeFrom(const ModuleConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.ModuleConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  components_.MergeFrom(from.components_);
  timer_components_.MergeFrom(from.timer_components_);
  if (from.has_module_library()) {
    set_has_module_library();
    module_library_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.module_library_);
  }
}

void ModuleConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.ModuleConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ModuleConfig::CopyFrom(const ModuleConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.ModuleConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ModuleConfig::IsInitialized() const {
  return true;
}

void ModuleConfig::Swap(ModuleConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ModuleConfig::InternalSwap(ModuleConfig* other) {
  components_.InternalSwap(&other->components_);
  timer_components_.InternalSwap(&other->timer_components_);
  module_library_.Swap(&other->module_library_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ModuleConfig::GetMetadata() const {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ModuleConfig

// optional string module_library = 1;
bool ModuleConfig::has_module_library() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ModuleConfig::set_has_module_library() {
  _has_bits_[0] |= 0x00000001u;
}
void ModuleConfig::clear_has_module_library() {
  _has_bits_[0] &= ~0x00000001u;
}
void ModuleConfig::clear_module_library() {
  module_library_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_module_library();
}
const ::std::string& ModuleConfig::module_library() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.module_library)
  return module_library_.GetNoArena();
}
void ModuleConfig::set_module_library(const ::std::string& value) {
  set_has_module_library();
  module_library_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ModuleConfig.module_library)
}
#if LANG_CXX11
void ModuleConfig::set_module_library(::std::string&& value) {
  set_has_module_library();
  module_library_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ModuleConfig.module_library)
}
#endif
void ModuleConfig::set_module_library(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_module_library();
  module_library_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ModuleConfig.module_library)
}
void ModuleConfig::set_module_library(const char* value, size_t size) {
  set_has_module_library();
  module_library_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ModuleConfig.module_library)
}
::std::string* ModuleConfig::mutable_module_library() {
  set_has_module_library();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.module_library)
  return module_library_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ModuleConfig::release_module_library() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ModuleConfig.module_library)
  clear_has_module_library();
  return module_library_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ModuleConfig::set_allocated_module_library(::std::string* module_library) {
  if (module_library != NULL) {
    set_has_module_library();
  } else {
    clear_has_module_library();
  }
  module_library_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), module_library);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ModuleConfig.module_library)
}

// repeated .apollo.cyber.proto.ComponentInfo components = 2;
int ModuleConfig::components_size() const {
  return components_.size();
}
void ModuleConfig::clear_components() {
  components_.Clear();
}
const ::apollo::cyber::proto::ComponentInfo& ModuleConfig::components(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.components)
  return components_.Get(index);
}
::apollo::cyber::proto::ComponentInfo* ModuleConfig::mutable_components(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.components)
  return components_.Mutable(index);
}
::apollo::cyber::proto::ComponentInfo* ModuleConfig::add_components() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.ModuleConfig.components)
  return components_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >*
ModuleConfig::mutable_components() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.ModuleConfig.components)
  return &components_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >&
ModuleConfig::components() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.ModuleConfig.components)
  return components_;
}

// repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
int ModuleConfig::timer_components_size() const {
  return timer_components_.size();
}
void ModuleConfig::clear_timer_components() {
  timer_components_.Clear();
}
const ::apollo::cyber::proto::TimerComponentInfo& ModuleConfig::timer_components(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Get(index);
}
::apollo::cyber::proto::TimerComponentInfo* ModuleConfig::mutable_timer_components(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Mutable(index);
}
::apollo::cyber::proto::TimerComponentInfo* ModuleConfig::add_timer_components() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >*
ModuleConfig::mutable_timer_components() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.ModuleConfig.timer_components)
  return &timer_components_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >&
ModuleConfig::timer_components() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DagConfig::kModuleConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DagConfig::DagConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.DagConfig)
}
DagConfig::DagConfig(const DagConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      module_config_(from.module_config_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.DagConfig)
}

void DagConfig::SharedCtor() {
  _cached_size_ = 0;
}

DagConfig::~DagConfig() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.DagConfig)
  SharedDtor();
}

void DagConfig::SharedDtor() {
}

void DagConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DagConfig::descriptor() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DagConfig& DagConfig::default_instance() {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::InitDefaults();
  return *internal_default_instance();
}

DagConfig* DagConfig::New(::google::protobuf::Arena* arena) const {
  DagConfig* n = new DagConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DagConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.DagConfig)
  module_config_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DagConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.DagConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_module_config()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.DagConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.DagConfig)
  return false;
#undef DO_
}

void DagConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.DagConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
  for (unsigned int i = 0, n = this->module_config_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->module_config(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.DagConfig)
}

::google::protobuf::uint8* DagConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.DagConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
  for (unsigned int i = 0, n = this->module_config_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->module_config(i), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.DagConfig)
  return target;
}

size_t DagConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.DagConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
  {
    unsigned int count = this->module_config_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->module_config(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DagConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.DagConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const DagConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DagConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.DagConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.DagConfig)
    MergeFrom(*source);
  }
}

void DagConfig::MergeFrom(const DagConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.DagConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  module_config_.MergeFrom(from.module_config_);
}

void DagConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.DagConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DagConfig::CopyFrom(const DagConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.DagConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DagConfig::IsInitialized() const {
  return true;
}

void DagConfig::Swap(DagConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DagConfig::InternalSwap(DagConfig* other) {
  module_config_.InternalSwap(&other->module_config_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DagConfig::GetMetadata() const {
  protobuf_cyber_2fproto_2fdag_5fconf_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fdag_5fconf_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DagConfig

// repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
int DagConfig::module_config_size() const {
  return module_config_.size();
}
void DagConfig::clear_module_config() {
  module_config_.Clear();
}
const ::apollo::cyber::proto::ModuleConfig& DagConfig::module_config(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Get(index);
}
::apollo::cyber::proto::ModuleConfig* DagConfig::mutable_module_config(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Mutable(index);
}
::apollo::cyber::proto::ModuleConfig* DagConfig::add_module_config() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >*
DagConfig::mutable_module_config() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.DagConfig.module_config)
  return &module_config_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >&
DagConfig::module_config() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.DagConfig.module_config)
  return module_config_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
