// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyber/proto/parameter.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cyber/proto/parameter.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace apollo {
namespace cyber {
namespace proto {
class ParamDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Param> {
  public:
  bool bool_value_;
  ::google::protobuf::int64 int_value_;
  double double_value_;
  ::google::protobuf::internal::ArenaStringPtr string_value_;
} _Param_default_instance_;
class NodeNameDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<NodeName> {
} _NodeName_default_instance_;
class ParamNameDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ParamName> {
} _ParamName_default_instance_;
class BoolResultDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<BoolResult> {
} _BoolResult_default_instance_;
class ParamsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Params> {
} _Params_default_instance_;

namespace protobuf_cyber_2fproto_2fparameter_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, type_name_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_Param_default_instance_), bool_value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_Param_default_instance_), int_value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_Param_default_instance_), double_value_),
  GOOGLE_PROTOBUF_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_Param_default_instance_), string_value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, proto_desc_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, oneof_value_),
  0,
  3,
  1,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeName, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeName, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NodeName, value_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamName, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamName, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ParamName, value_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BoolResult, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BoolResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BoolResult, value_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, param_),
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 14, sizeof(Param)},
  { 22, 28, sizeof(NodeName)},
  { 29, 35, sizeof(ParamName)},
  { 36, 42, sizeof(BoolResult)},
  { 43, 49, sizeof(Params)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Param_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_NodeName_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ParamName_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_BoolResult_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Params_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cyber/proto/parameter.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

}  // namespace

void TableStruct::Shutdown() {
  _Param_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _NodeName_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _ParamName_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _BoolResult_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _Params_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Param_default_instance_.DefaultConstruct();
  _NodeName_default_instance_.DefaultConstruct();
  _ParamName_default_instance_.DefaultConstruct();
  _BoolResult_default_instance_.DefaultConstruct();
  _Params_default_instance_.DefaultConstruct();
  _Param_default_instance_.bool_value_ = false;
  _Param_default_instance_.int_value_ = GOOGLE_LONGLONG(0);
  _Param_default_instance_.double_value_ = 0;
  _Param_default_instance_.string_value_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\033cyber/proto/parameter.proto\022\022apollo.cy"
      "ber.proto\"\323\001\n\005Param\022\014\n\004name\030\001 \001(\t\022+\n\004typ"
      "e\030\002 \001(\0162\035.apollo.cyber.proto.ParamType\022\021"
      "\n\ttype_name\030\003 \001(\t\022\024\n\nbool_value\030\004 \001(\010H\000\022"
      "\023\n\tint_value\030\005 \001(\003H\000\022\026\n\014double_value\030\006 \001"
      "(\001H\000\022\026\n\014string_value\030\007 \001(\tH\000\022\022\n\nproto_de"
      "sc\030\010 \001(\014B\r\n\013oneof_value\"\031\n\010NodeName\022\r\n\005v"
      "alue\030\001 \001(\t\"\032\n\tParamName\022\r\n\005value\030\001 \001(\t\"\033"
      "\n\nBoolResult\022\r\n\005value\030\001 \001(\010\"2\n\006Params\022(\n"
      "\005param\030\001 \003(\0132\031.apollo.cyber.proto.Param*"
      "Q\n\tParamType\022\013\n\007NOT_SET\020\000\022\010\n\004BOOL\020\001\022\007\n\003I"
      "NT\020\002\022\n\n\006DOUBLE\020\003\022\n\n\006STRING\020\004\022\014\n\010PROTOBUF"
      "\020\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 482);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cyber/proto/parameter.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cyber_2fproto_2fparameter_2eproto

const ::google::protobuf::EnumDescriptor* ParamType_descriptor() {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_enum_descriptors[0];
}
bool ParamType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Param::kNameFieldNumber;
const int Param::kTypeFieldNumber;
const int Param::kTypeNameFieldNumber;
const int Param::kBoolValueFieldNumber;
const int Param::kIntValueFieldNumber;
const int Param::kDoubleValueFieldNumber;
const int Param::kStringValueFieldNumber;
const int Param::kProtoDescFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Param::Param()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.Param)
}
Param::Param(const Param& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  type_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_type_name()) {
    type_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_name_);
  }
  proto_desc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_proto_desc()) {
    proto_desc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.proto_desc_);
  }
  type_ = from.type_;
  clear_has_oneof_value();
  switch (from.oneof_value_case()) {
    case kBoolValue: {
      set_bool_value(from.bool_value());
      break;
    }
    case kIntValue: {
      set_int_value(from.int_value());
      break;
    }
    case kDoubleValue: {
      set_double_value(from.double_value());
      break;
    }
    case kStringValue: {
      set_string_value(from.string_value());
      break;
    }
    case ONEOF_VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.Param)
}

void Param::SharedCtor() {
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  proto_desc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
  clear_has_oneof_value();
}

Param::~Param() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.Param)
  SharedDtor();
}

void Param::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  proto_desc_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_oneof_value()) {
    clear_oneof_value();
  }
}

void Param::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Param::descriptor() {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Param& Param::default_instance() {
  protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  return *internal_default_instance();
}

Param* Param::New(::google::protobuf::Arena* arena) const {
  Param* n = new Param;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Param::clear_oneof_value() {
// @@protoc_insertion_point(one_of_clear_start:apollo.cyber.proto.Param)
  switch (oneof_value_case()) {
    case kBoolValue: {
      // No need to clear
      break;
    }
    case kIntValue: {
      // No need to clear
      break;
    }
    case kDoubleValue: {
      // No need to clear
      break;
    }
    case kStringValue: {
      oneof_value_.string_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case ONEOF_VALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = ONEOF_VALUE_NOT_SET;
}


void Param::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.Param)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_name()) {
      GOOGLE_DCHECK(!name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*name_.UnsafeRawStringPointer())->clear();
    }
    if (has_type_name()) {
      GOOGLE_DCHECK(!type_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*type_name_.UnsafeRawStringPointer())->clear();
    }
    if (has_proto_desc()) {
      GOOGLE_DCHECK(!proto_desc_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*proto_desc_.UnsafeRawStringPointer())->clear();
    }
  }
  type_ = 0;
  clear_oneof_value();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Param::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.Param)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.Param.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.cyber.proto.ParamType type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::cyber::proto::ParamType_IsValid(value)) {
            set_type(static_cast< ::apollo::cyber::proto::ParamType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string type_name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type_name().data(), this->type_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.Param.type_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool bool_value = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          clear_oneof_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &oneof_value_.bool_value_)));
          set_has_bool_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 int_value = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {
          clear_oneof_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &oneof_value_.int_value_)));
          set_has_int_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double double_value = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u)) {
          clear_oneof_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &oneof_value_.double_value_)));
          set_has_double_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string string_value = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->string_value().data(), this->string_value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.Param.string_value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes proto_desc = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_proto_desc()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.Param)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.Param)
  return false;
#undef DO_
}

void Param::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.Param)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.Param.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional .apollo.cyber.proto.ParamType type = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // optional string type_name = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type_name().data(), this->type_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.Param.type_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->type_name(), output);
  }

  switch (oneof_value_case()) {
    case kBoolValue:
      ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->bool_value(), output);
      break;
    case kIntValue:
      ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->int_value(), output);
      break;
    case kDoubleValue:
      ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->double_value(), output);
      break;
    case kStringValue:
      ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
        this->string_value().data(), this->string_value().length(),
        ::google::protobuf::internal::WireFormat::SERIALIZE,
        "apollo.cyber.proto.Param.string_value");
      ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
        7, this->string_value(), output);
      break;
    default: ;
  }
  // optional bytes proto_desc = 8;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      8, this->proto_desc(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.Param)
}

::google::protobuf::uint8* Param::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.Param)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.Param.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional .apollo.cyber.proto.ParamType type = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // optional string type_name = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type_name().data(), this->type_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.Param.type_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->type_name(), target);
  }

  switch (oneof_value_case()) {
    case kBoolValue:
      target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->bool_value(), target);
      break;
    case kIntValue:
      target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->int_value(), target);
      break;
    case kDoubleValue:
      target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->double_value(), target);
      break;
    case kStringValue:
      ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
        this->string_value().data(), this->string_value().length(),
        ::google::protobuf::internal::WireFormat::SERIALIZE,
        "apollo.cyber.proto.Param.string_value");
      target =
        ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
          7, this->string_value(), target);
      break;
    default: ;
  }
  // optional bytes proto_desc = 8;
  if (cached_has_bits & 0x00000004u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        8, this->proto_desc(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.Param)
  return target;
}

size_t Param::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.Param)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string type_name = 3;
    if (has_type_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type_name());
    }

    // optional bytes proto_desc = 8;
    if (has_proto_desc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->proto_desc());
    }

    // optional .apollo.cyber.proto.ParamType type = 2;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  switch (oneof_value_case()) {
    // optional bool bool_value = 4;
    case kBoolValue: {
      total_size += 1 + 1;
      break;
    }
    // optional int64 int_value = 5;
    case kIntValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->int_value());
      break;
    }
    // optional double double_value = 6;
    case kDoubleValue: {
      total_size += 1 + 8;
      break;
    }
    // optional string string_value = 7;
    case kStringValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->string_value());
      break;
    }
    case ONEOF_VALUE_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Param::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.Param)
  GOOGLE_DCHECK_NE(&from, this);
  const Param* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Param>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.Param)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.Param)
    MergeFrom(*source);
  }
}

void Param::MergeFrom(const Param& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.Param)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_type_name();
      type_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_name_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_proto_desc();
      proto_desc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.proto_desc_);
    }
    if (cached_has_bits & 0x00000008u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  switch (from.oneof_value_case()) {
    case kBoolValue: {
      set_bool_value(from.bool_value());
      break;
    }
    case kIntValue: {
      set_int_value(from.int_value());
      break;
    }
    case kDoubleValue: {
      set_double_value(from.double_value());
      break;
    }
    case kStringValue: {
      set_string_value(from.string_value());
      break;
    }
    case ONEOF_VALUE_NOT_SET: {
      break;
    }
  }
}

void Param::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Param::CopyFrom(const Param& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Param::IsInitialized() const {
  return true;
}

void Param::Swap(Param* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Param::InternalSwap(Param* other) {
  name_.Swap(&other->name_);
  type_name_.Swap(&other->type_name_);
  proto_desc_.Swap(&other->proto_desc_);
  std::swap(type_, other->type_);
  std::swap(oneof_value_, other->oneof_value_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Param::GetMetadata() const {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Param

// optional string name = 1;
bool Param::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Param::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void Param::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void Param::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
const ::std::string& Param::name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.name)
  return name_.GetNoArena();
}
void Param::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.name)
}
#if LANG_CXX11
void Param::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.name)
}
#endif
void Param::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.name)
}
void Param::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.name)
}
::std::string* Param::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Param::release_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Param::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.name)
}

// optional .apollo.cyber.proto.ParamType type = 2;
bool Param::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void Param::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
void Param::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
void Param::clear_type() {
  type_ = 0;
  clear_has_type();
}
::apollo::cyber::proto::ParamType Param::type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.type)
  return static_cast< ::apollo::cyber::proto::ParamType >(type_);
}
void Param::set_type(::apollo::cyber::proto::ParamType value) {
  assert(::apollo::cyber::proto::ParamType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.type)
}

// optional string type_name = 3;
bool Param::has_type_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Param::set_has_type_name() {
  _has_bits_[0] |= 0x00000002u;
}
void Param::clear_has_type_name() {
  _has_bits_[0] &= ~0x00000002u;
}
void Param::clear_type_name() {
  type_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type_name();
}
const ::std::string& Param::type_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.type_name)
  return type_name_.GetNoArena();
}
void Param::set_type_name(const ::std::string& value) {
  set_has_type_name();
  type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.type_name)
}
#if LANG_CXX11
void Param::set_type_name(::std::string&& value) {
  set_has_type_name();
  type_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.type_name)
}
#endif
void Param::set_type_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_type_name();
  type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.type_name)
}
void Param::set_type_name(const char* value, size_t size) {
  set_has_type_name();
  type_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.type_name)
}
::std::string* Param::mutable_type_name() {
  set_has_type_name();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.type_name)
  return type_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Param::release_type_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.type_name)
  clear_has_type_name();
  return type_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Param::set_allocated_type_name(::std::string* type_name) {
  if (type_name != NULL) {
    set_has_type_name();
  } else {
    clear_has_type_name();
  }
  type_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.type_name)
}

// optional bool bool_value = 4;
bool Param::has_bool_value() const {
  return oneof_value_case() == kBoolValue;
}
void Param::set_has_bool_value() {
  _oneof_case_[0] = kBoolValue;
}
void Param::clear_bool_value() {
  if (has_bool_value()) {
    oneof_value_.bool_value_ = false;
    clear_has_oneof_value();
  }
}
bool Param::bool_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.bool_value)
  if (has_bool_value()) {
    return oneof_value_.bool_value_;
  }
  return false;
}
void Param::set_bool_value(bool value) {
  if (!has_bool_value()) {
    clear_oneof_value();
    set_has_bool_value();
  }
  oneof_value_.bool_value_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.bool_value)
}

// optional int64 int_value = 5;
bool Param::has_int_value() const {
  return oneof_value_case() == kIntValue;
}
void Param::set_has_int_value() {
  _oneof_case_[0] = kIntValue;
}
void Param::clear_int_value() {
  if (has_int_value()) {
    oneof_value_.int_value_ = GOOGLE_LONGLONG(0);
    clear_has_oneof_value();
  }
}
::google::protobuf::int64 Param::int_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.int_value)
  if (has_int_value()) {
    return oneof_value_.int_value_;
  }
  return GOOGLE_LONGLONG(0);
}
void Param::set_int_value(::google::protobuf::int64 value) {
  if (!has_int_value()) {
    clear_oneof_value();
    set_has_int_value();
  }
  oneof_value_.int_value_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.int_value)
}

// optional double double_value = 6;
bool Param::has_double_value() const {
  return oneof_value_case() == kDoubleValue;
}
void Param::set_has_double_value() {
  _oneof_case_[0] = kDoubleValue;
}
void Param::clear_double_value() {
  if (has_double_value()) {
    oneof_value_.double_value_ = 0;
    clear_has_oneof_value();
  }
}
double Param::double_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.double_value)
  if (has_double_value()) {
    return oneof_value_.double_value_;
  }
  return 0;
}
void Param::set_double_value(double value) {
  if (!has_double_value()) {
    clear_oneof_value();
    set_has_double_value();
  }
  oneof_value_.double_value_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.double_value)
}

// optional string string_value = 7;
bool Param::has_string_value() const {
  return oneof_value_case() == kStringValue;
}
void Param::set_has_string_value() {
  _oneof_case_[0] = kStringValue;
}
void Param::clear_string_value() {
  if (has_string_value()) {
    oneof_value_.string_value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_oneof_value();
  }
}
const ::std::string& Param::string_value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.string_value)
  if (has_string_value()) {
    return oneof_value_.string_value_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void Param::set_string_value(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.string_value)
  if (!has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.string_value)
}
#if LANG_CXX11
void Param::set_string_value(::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.string_value)
  if (!has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.string_value)
}
#endif
void Param::set_string_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.string_value)
}
void Param::set_string_value(const char* value, size_t size) {
  if (!has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  oneof_value_.string_value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.string_value)
}
::std::string* Param::mutable_string_value() {
  if (!has_string_value()) {
    clear_oneof_value();
    set_has_string_value();
    oneof_value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.string_value)
  return oneof_value_.string_value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Param::release_string_value() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.string_value)
  if (has_string_value()) {
    clear_has_oneof_value();
    return oneof_value_.string_value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void Param::set_allocated_string_value(::std::string* string_value) {
  if (!has_string_value()) {
    oneof_value_.string_value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_oneof_value();
  if (string_value != NULL) {
    set_has_string_value();
    oneof_value_.string_value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        string_value);
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.string_value)
}

// optional bytes proto_desc = 8;
bool Param::has_proto_desc() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void Param::set_has_proto_desc() {
  _has_bits_[0] |= 0x00000004u;
}
void Param::clear_has_proto_desc() {
  _has_bits_[0] &= ~0x00000004u;
}
void Param::clear_proto_desc() {
  proto_desc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_proto_desc();
}
const ::std::string& Param::proto_desc() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Param.proto_desc)
  return proto_desc_.GetNoArena();
}
void Param::set_proto_desc(const ::std::string& value) {
  set_has_proto_desc();
  proto_desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Param.proto_desc)
}
#if LANG_CXX11
void Param::set_proto_desc(::std::string&& value) {
  set_has_proto_desc();
  proto_desc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.Param.proto_desc)
}
#endif
void Param::set_proto_desc(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_proto_desc();
  proto_desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.Param.proto_desc)
}
void Param::set_proto_desc(const void* value, size_t size) {
  set_has_proto_desc();
  proto_desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.Param.proto_desc)
}
::std::string* Param::mutable_proto_desc() {
  set_has_proto_desc();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Param.proto_desc)
  return proto_desc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Param::release_proto_desc() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Param.proto_desc)
  clear_has_proto_desc();
  return proto_desc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Param::set_allocated_proto_desc(::std::string* proto_desc) {
  if (proto_desc != NULL) {
    set_has_proto_desc();
  } else {
    clear_has_proto_desc();
  }
  proto_desc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), proto_desc);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Param.proto_desc)
}

bool Param::has_oneof_value() const {
  return oneof_value_case() != ONEOF_VALUE_NOT_SET;
}
void Param::clear_has_oneof_value() {
  _oneof_case_[0] = ONEOF_VALUE_NOT_SET;
}
Param::OneofValueCase Param::oneof_value_case() const {
  return Param::OneofValueCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NodeName::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NodeName::NodeName()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.NodeName)
}
NodeName::NodeName(const NodeName& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_value()) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.NodeName)
}

void NodeName::SharedCtor() {
  _cached_size_ = 0;
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

NodeName::~NodeName() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.NodeName)
  SharedDtor();
}

void NodeName::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NodeName::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NodeName::descriptor() {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NodeName& NodeName::default_instance() {
  protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  return *internal_default_instance();
}

NodeName* NodeName::New(::google::protobuf::Arena* arena) const {
  NodeName* n = new NodeName;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NodeName::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.NodeName)
  if (has_value()) {
    GOOGLE_DCHECK(!value_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*value_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NodeName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.NodeName)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.NodeName.value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.NodeName)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.NodeName)
  return false;
#undef DO_
}

void NodeName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.NodeName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string value = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.NodeName.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.NodeName)
}

::google::protobuf::uint8* NodeName::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.NodeName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string value = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.NodeName.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.NodeName)
  return target;
}

size_t NodeName::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.NodeName)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional string value = 1;
  if (has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NodeName::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.NodeName)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeName* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NodeName>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.NodeName)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.NodeName)
    MergeFrom(*source);
  }
}

void NodeName::MergeFrom(const NodeName& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.NodeName)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_value()) {
    set_has_value();
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void NodeName::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.NodeName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeName::CopyFrom(const NodeName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.NodeName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeName::IsInitialized() const {
  return true;
}

void NodeName::Swap(NodeName* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NodeName::InternalSwap(NodeName* other) {
  value_.Swap(&other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NodeName::GetMetadata() const {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NodeName

// optional string value = 1;
bool NodeName::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void NodeName::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
void NodeName::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
void NodeName::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
const ::std::string& NodeName::value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.NodeName.value)
  return value_.GetNoArena();
}
void NodeName::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.NodeName.value)
}
#if LANG_CXX11
void NodeName::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.NodeName.value)
}
#endif
void NodeName::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.NodeName.value)
}
void NodeName::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.NodeName.value)
}
::std::string* NodeName::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.NodeName.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* NodeName::release_value() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.NodeName.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void NodeName::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.NodeName.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParamName::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParamName::ParamName()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.ParamName)
}
ParamName::ParamName(const ParamName& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_value()) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.ParamName)
}

void ParamName::SharedCtor() {
  _cached_size_ = 0;
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ParamName::~ParamName() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.ParamName)
  SharedDtor();
}

void ParamName::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ParamName::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ParamName::descriptor() {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParamName& ParamName::default_instance() {
  protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  return *internal_default_instance();
}

ParamName* ParamName::New(::google::protobuf::Arena* arena) const {
  ParamName* n = new ParamName;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ParamName::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.ParamName)
  if (has_value()) {
    GOOGLE_DCHECK(!value_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*value_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParamName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.ParamName)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.cyber.proto.ParamName.value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.ParamName)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.ParamName)
  return false;
#undef DO_
}

void ParamName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.ParamName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string value = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.ParamName.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.ParamName)
}

::google::protobuf::uint8* ParamName::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.ParamName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string value = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.cyber.proto.ParamName.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.ParamName)
  return target;
}

size_t ParamName::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.ParamName)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional string value = 1;
  if (has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ParamName::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.ParamName)
  GOOGLE_DCHECK_NE(&from, this);
  const ParamName* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParamName>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.ParamName)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.ParamName)
    MergeFrom(*source);
  }
}

void ParamName::MergeFrom(const ParamName& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.ParamName)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_value()) {
    set_has_value();
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void ParamName::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.ParamName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParamName::CopyFrom(const ParamName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.ParamName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParamName::IsInitialized() const {
  return true;
}

void ParamName::Swap(ParamName* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParamName::InternalSwap(ParamName* other) {
  value_.Swap(&other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ParamName::GetMetadata() const {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ParamName

// optional string value = 1;
bool ParamName::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ParamName::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
void ParamName::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
void ParamName::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
const ::std::string& ParamName::value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ParamName.value)
  return value_.GetNoArena();
}
void ParamName::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ParamName.value)
}
#if LANG_CXX11
void ParamName::set_value(::std::string&& value) {
  set_has_value();
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ParamName.value)
}
#endif
void ParamName::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ParamName.value)
}
void ParamName::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ParamName.value)
}
::std::string* ParamName::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ParamName.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ParamName::release_value() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ParamName.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ParamName::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ParamName.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BoolResult::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BoolResult::BoolResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.BoolResult)
}
BoolResult::BoolResult(const BoolResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.BoolResult)
}

void BoolResult::SharedCtor() {
  _cached_size_ = 0;
  value_ = false;
}

BoolResult::~BoolResult() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.BoolResult)
  SharedDtor();
}

void BoolResult::SharedDtor() {
}

void BoolResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BoolResult::descriptor() {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BoolResult& BoolResult::default_instance() {
  protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  return *internal_default_instance();
}

BoolResult* BoolResult::New(::google::protobuf::Arena* arena) const {
  BoolResult* n = new BoolResult;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BoolResult::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.BoolResult)
  value_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool BoolResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.BoolResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.BoolResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.BoolResult)
  return false;
#undef DO_
}

void BoolResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.BoolResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool value = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.BoolResult)
}

::google::protobuf::uint8* BoolResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.BoolResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool value = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.BoolResult)
  return target;
}

size_t BoolResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.BoolResult)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // optional bool value = 1;
  if (has_value()) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BoolResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.BoolResult)
  GOOGLE_DCHECK_NE(&from, this);
  const BoolResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BoolResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.BoolResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.BoolResult)
    MergeFrom(*source);
  }
}

void BoolResult::MergeFrom(const BoolResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.BoolResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_value()) {
    set_value(from.value());
  }
}

void BoolResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.BoolResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BoolResult::CopyFrom(const BoolResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.BoolResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoolResult::IsInitialized() const {
  return true;
}

void BoolResult::Swap(BoolResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BoolResult::InternalSwap(BoolResult* other) {
  std::swap(value_, other->value_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BoolResult::GetMetadata() const {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BoolResult

// optional bool value = 1;
bool BoolResult::has_value() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void BoolResult::set_has_value() {
  _has_bits_[0] |= 0x00000001u;
}
void BoolResult::clear_has_value() {
  _has_bits_[0] &= ~0x00000001u;
}
void BoolResult::clear_value() {
  value_ = false;
  clear_has_value();
}
bool BoolResult::value() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.BoolResult.value)
  return value_;
}
void BoolResult::set_value(bool value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.BoolResult.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Params::kParamFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Params::Params()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.cyber.proto.Params)
}
Params::Params(const Params& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      param_(from.param_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.cyber.proto.Params)
}

void Params::SharedCtor() {
  _cached_size_ = 0;
}

Params::~Params() {
  // @@protoc_insertion_point(destructor:apollo.cyber.proto.Params)
  SharedDtor();
}

void Params::SharedDtor() {
}

void Params::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Params::descriptor() {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Params& Params::default_instance() {
  protobuf_cyber_2fproto_2fparameter_2eproto::InitDefaults();
  return *internal_default_instance();
}

Params* Params::New(::google::protobuf::Arena* arena) const {
  Params* n = new Params;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Params::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.cyber.proto.Params)
  param_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Params::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.cyber.proto.Params)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.cyber.proto.Param param = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_param()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.cyber.proto.Params)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.cyber.proto.Params)
  return false;
#undef DO_
}

void Params::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.cyber.proto.Params)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.cyber.proto.Param param = 1;
  for (unsigned int i = 0, n = this->param_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->param(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.cyber.proto.Params)
}

::google::protobuf::uint8* Params::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:apollo.cyber.proto.Params)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.cyber.proto.Param param = 1;
  for (unsigned int i = 0, n = this->param_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->param(i), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.cyber.proto.Params)
  return target;
}

size_t Params::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.cyber.proto.Params)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .apollo.cyber.proto.Param param = 1;
  {
    unsigned int count = this->param_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->param(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Params::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.cyber.proto.Params)
  GOOGLE_DCHECK_NE(&from, this);
  const Params* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Params>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.cyber.proto.Params)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.cyber.proto.Params)
    MergeFrom(*source);
  }
}

void Params::MergeFrom(const Params& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.cyber.proto.Params)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  param_.MergeFrom(from.param_);
}

void Params::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.cyber.proto.Params)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Params::CopyFrom(const Params& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.cyber.proto.Params)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Params::IsInitialized() const {
  return true;
}

void Params::Swap(Params* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Params::InternalSwap(Params* other) {
  param_.InternalSwap(&other->param_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Params::GetMetadata() const {
  protobuf_cyber_2fproto_2fparameter_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cyber_2fproto_2fparameter_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Params

// repeated .apollo.cyber.proto.Param param = 1;
int Params::param_size() const {
  return param_.size();
}
void Params::clear_param() {
  param_.Clear();
}
const ::apollo::cyber::proto::Param& Params::param(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Params.param)
  return param_.Get(index);
}
::apollo::cyber::proto::Param* Params::mutable_param(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Params.param)
  return param_.Mutable(index);
}
::apollo::cyber::proto::Param* Params::add_param() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.Params.param)
  return param_.Add();
}
::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::Param >*
Params::mutable_param() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.Params.param)
  return &param_;
}
const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::Param >&
Params::param() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.Params.param)
  return param_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)
