// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyber/proto/topology_change.proto

#ifndef PROTOBUF_cyber_2fproto_2ftopology_5fchange_2eproto__INCLUDED
#define PROTOBUF_cyber_2fproto_2ftopology_5fchange_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "cyber/proto/role_attributes.pb.h"
// @@protoc_insertion_point(includes)
namespace apollo {
namespace cyber {
namespace proto {
class ChangeMsg;
class ChangeMsgDefaultTypeInternal;
extern ChangeMsgDefaultTypeInternal _ChangeMsg_default_instance_;
class RoleAttributes;
class RoleAttributesDefaultTypeInternal;
extern RoleAttributesDefaultTypeInternal _RoleAttributes_default_instance_;
class SocketAddr;
class SocketAddrDefaultTypeInternal;
extern SocketAddrDefaultTypeInternal _SocketAddr_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo

namespace apollo {
namespace cyber {
namespace proto {

namespace protobuf_cyber_2fproto_2ftopology_5fchange_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cyber_2fproto_2ftopology_5fchange_2eproto

enum ChangeType {
  CHANGE_NODE = 1,
  CHANGE_CHANNEL = 2,
  CHANGE_SERVICE = 3,
  CHANGE_PARTICIPANT = 4
};
bool ChangeType_IsValid(int value);
const ChangeType ChangeType_MIN = CHANGE_NODE;
const ChangeType ChangeType_MAX = CHANGE_PARTICIPANT;
const int ChangeType_ARRAYSIZE = ChangeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChangeType_descriptor();
inline const ::std::string& ChangeType_Name(ChangeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChangeType_descriptor(), value);
}
inline bool ChangeType_Parse(
    const ::std::string& name, ChangeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChangeType>(
    ChangeType_descriptor(), name, value);
}
enum OperateType {
  OPT_JOIN = 1,
  OPT_LEAVE = 2
};
bool OperateType_IsValid(int value);
const OperateType OperateType_MIN = OPT_JOIN;
const OperateType OperateType_MAX = OPT_LEAVE;
const int OperateType_ARRAYSIZE = OperateType_MAX + 1;

const ::google::protobuf::EnumDescriptor* OperateType_descriptor();
inline const ::std::string& OperateType_Name(OperateType value) {
  return ::google::protobuf::internal::NameOfEnum(
    OperateType_descriptor(), value);
}
inline bool OperateType_Parse(
    const ::std::string& name, OperateType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OperateType>(
    OperateType_descriptor(), name, value);
}
enum RoleType {
  ROLE_NODE = 1,
  ROLE_WRITER = 2,
  ROLE_READER = 3,
  ROLE_SERVER = 4,
  ROLE_CLIENT = 5,
  ROLE_PARTICIPANT = 6
};
bool RoleType_IsValid(int value);
const RoleType RoleType_MIN = ROLE_NODE;
const RoleType RoleType_MAX = ROLE_PARTICIPANT;
const int RoleType_ARRAYSIZE = RoleType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RoleType_descriptor();
inline const ::std::string& RoleType_Name(RoleType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RoleType_descriptor(), value);
}
inline bool RoleType_Parse(
    const ::std::string& name, RoleType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RoleType>(
    RoleType_descriptor(), name, value);
}
// ===================================================================

class ChangeMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ChangeMsg) */ {
 public:
  ChangeMsg();
  virtual ~ChangeMsg();

  ChangeMsg(const ChangeMsg& from);

  inline ChangeMsg& operator=(const ChangeMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChangeMsg& default_instance();

  static inline const ChangeMsg* internal_default_instance() {
    return reinterpret_cast<const ChangeMsg*>(
               &_ChangeMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ChangeMsg* other);

  // implements Message ----------------------------------------------

  inline ChangeMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  ChangeMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ChangeMsg& from);
  void MergeFrom(const ChangeMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ChangeMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.cyber.proto.RoleAttributes role_attr = 5;
  bool has_role_attr() const;
  void clear_role_attr();
  static const int kRoleAttrFieldNumber = 5;
  const ::apollo::cyber::proto::RoleAttributes& role_attr() const;
  ::apollo::cyber::proto::RoleAttributes* mutable_role_attr();
  ::apollo::cyber::proto::RoleAttributes* release_role_attr();
  void set_allocated_role_attr(::apollo::cyber::proto::RoleAttributes* role_attr);

  // optional uint64 timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // optional .apollo.cyber.proto.RoleType role_type = 4;
  bool has_role_type() const;
  void clear_role_type();
  static const int kRoleTypeFieldNumber = 4;
  ::apollo::cyber::proto::RoleType role_type() const;
  void set_role_type(::apollo::cyber::proto::RoleType value);

  // optional .apollo.cyber.proto.ChangeType change_type = 2;
  bool has_change_type() const;
  void clear_change_type();
  static const int kChangeTypeFieldNumber = 2;
  ::apollo::cyber::proto::ChangeType change_type() const;
  void set_change_type(::apollo::cyber::proto::ChangeType value);

  // optional .apollo.cyber.proto.OperateType operate_type = 3;
  bool has_operate_type() const;
  void clear_operate_type();
  static const int kOperateTypeFieldNumber = 3;
  ::apollo::cyber::proto::OperateType operate_type() const;
  void set_operate_type(::apollo::cyber::proto::OperateType value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ChangeMsg)
 private:
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_change_type();
  void clear_has_change_type();
  void set_has_operate_type();
  void clear_has_operate_type();
  void set_has_role_type();
  void clear_has_role_type();
  void set_has_role_attr();
  void clear_has_role_attr();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::apollo::cyber::proto::RoleAttributes* role_attr_;
  ::google::protobuf::uint64 timestamp_;
  int role_type_;
  int change_type_;
  int operate_type_;
  friend struct protobuf_cyber_2fproto_2ftopology_5fchange_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ChangeMsg

// optional uint64 timestamp = 1;
inline bool ChangeMsg::has_timestamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ChangeMsg::set_has_timestamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ChangeMsg::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ChangeMsg::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 ChangeMsg::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ChangeMsg.timestamp)
  return timestamp_;
}
inline void ChangeMsg::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ChangeMsg.timestamp)
}

// optional .apollo.cyber.proto.ChangeType change_type = 2;
inline bool ChangeMsg::has_change_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ChangeMsg::set_has_change_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ChangeMsg::clear_has_change_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ChangeMsg::clear_change_type() {
  change_type_ = 1;
  clear_has_change_type();
}
inline ::apollo::cyber::proto::ChangeType ChangeMsg::change_type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ChangeMsg.change_type)
  return static_cast< ::apollo::cyber::proto::ChangeType >(change_type_);
}
inline void ChangeMsg::set_change_type(::apollo::cyber::proto::ChangeType value) {
  assert(::apollo::cyber::proto::ChangeType_IsValid(value));
  set_has_change_type();
  change_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ChangeMsg.change_type)
}

// optional .apollo.cyber.proto.OperateType operate_type = 3;
inline bool ChangeMsg::has_operate_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ChangeMsg::set_has_operate_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ChangeMsg::clear_has_operate_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ChangeMsg::clear_operate_type() {
  operate_type_ = 1;
  clear_has_operate_type();
}
inline ::apollo::cyber::proto::OperateType ChangeMsg::operate_type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ChangeMsg.operate_type)
  return static_cast< ::apollo::cyber::proto::OperateType >(operate_type_);
}
inline void ChangeMsg::set_operate_type(::apollo::cyber::proto::OperateType value) {
  assert(::apollo::cyber::proto::OperateType_IsValid(value));
  set_has_operate_type();
  operate_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ChangeMsg.operate_type)
}

// optional .apollo.cyber.proto.RoleType role_type = 4;
inline bool ChangeMsg::has_role_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ChangeMsg::set_has_role_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ChangeMsg::clear_has_role_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ChangeMsg::clear_role_type() {
  role_type_ = 1;
  clear_has_role_type();
}
inline ::apollo::cyber::proto::RoleType ChangeMsg::role_type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ChangeMsg.role_type)
  return static_cast< ::apollo::cyber::proto::RoleType >(role_type_);
}
inline void ChangeMsg::set_role_type(::apollo::cyber::proto::RoleType value) {
  assert(::apollo::cyber::proto::RoleType_IsValid(value));
  set_has_role_type();
  role_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ChangeMsg.role_type)
}

// optional .apollo.cyber.proto.RoleAttributes role_attr = 5;
inline bool ChangeMsg::has_role_attr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ChangeMsg::set_has_role_attr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ChangeMsg::clear_has_role_attr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ChangeMsg::clear_role_attr() {
  if (role_attr_ != NULL) role_attr_->::apollo::cyber::proto::RoleAttributes::Clear();
  clear_has_role_attr();
}
inline const ::apollo::cyber::proto::RoleAttributes& ChangeMsg::role_attr() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ChangeMsg.role_attr)
  return role_attr_ != NULL ? *role_attr_
                         : *::apollo::cyber::proto::RoleAttributes::internal_default_instance();
}
inline ::apollo::cyber::proto::RoleAttributes* ChangeMsg::mutable_role_attr() {
  set_has_role_attr();
  if (role_attr_ == NULL) {
    role_attr_ = new ::apollo::cyber::proto::RoleAttributes;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ChangeMsg.role_attr)
  return role_attr_;
}
inline ::apollo::cyber::proto::RoleAttributes* ChangeMsg::release_role_attr() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ChangeMsg.role_attr)
  clear_has_role_attr();
  ::apollo::cyber::proto::RoleAttributes* temp = role_attr_;
  role_attr_ = NULL;
  return temp;
}
inline void ChangeMsg::set_allocated_role_attr(::apollo::cyber::proto::RoleAttributes* role_attr) {
  delete role_attr_;
  role_attr_ = role_attr;
  if (role_attr) {
    set_has_role_attr();
  } else {
    clear_has_role_attr();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ChangeMsg.role_attr)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace cyber
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::cyber::proto::ChangeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::cyber::proto::ChangeType>() {
  return ::apollo::cyber::proto::ChangeType_descriptor();
}
template <> struct is_proto_enum< ::apollo::cyber::proto::OperateType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::cyber::proto::OperateType>() {
  return ::apollo::cyber::proto::OperateType_descriptor();
}
template <> struct is_proto_enum< ::apollo::cyber::proto::RoleType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::cyber::proto::RoleType>() {
  return ::apollo::cyber::proto::RoleType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cyber_2fproto_2ftopology_5fchange_2eproto__INCLUDED
